"""MoSDeR source adapters, visual injection, TriLoRA, and F/G/R training.

Start with ``core``, ``bridge``, and ``routing`` for the model, then
``training`` and ``objectives`` for the training stages."""

from .bridge import (
    DualSourceExplicitResidual,
    MoSDeRVisualBridge,
    VisualBridgeOutput,
)
from .contract import (
    ARCHITECTURE_VERSION,
    HOLD_STATUS,
    IMPLEMENTATION_EVIDENCE,
    METHOD_SPEC_ID,
    PUBLIC_METHOD_NAME,
    SUPPORTED_FAMILIES,
    TARGET_FAMILIES,
    architecture_contract,
    validate_contract,
)
from .core import MoSDeRMotionSourceCore, MotionSourceOutput
from .family_backend import (
    BackendStageConfiguration,
    MOSDER_BACKEND_TYPES,
    MolmoMoSDeRBackend,
    MoSDeRBackendError,
    MoSDeRFamilyBackendProtocol,
    NVILAMoSDeRBackend,
    QwenMoSDeRBackend,
    assemble_mosder_backend,
    assert_mosder_frozen_base_unchanged,
    load_local_mosder_backend,
    method_parameter_ids,
    snapshot_mosder_frozen_base,
)
from .factor_training import (
    ExactStageFTwoPassResult,
    FactorTrainingContractError,
    StageFCandidateTexts,
    exact_two_pass_stage_f_backward,
)
from .language import (
    CANONICAL_ANSWERS,
    CanonicalLanguagePlan,
    LanguagePlanContractError,
    ParsedMotionLanguage,
    canonical_answer,
    parse_four_line_language,
    plan_canonical_language,
    validate_language_plan,
    validate_score_against_plan,
)
from .objectives import (
    FourLineLanguageLoss,
    LANGUAGE_SPAN_ORDER,
    LANGUAGE_SPAN_WEIGHT,
    ObjectiveContractError,
    StageFFactorLoss,
    four_line_language_span_loss,
    stage_f_factor_loss,
    stage_g_language_loss,
    stage_r_language_loss,
)
from .optimizer import (
    OptimizerContractError,
    audit_stage_adamw,
    build_stage_adamw,
)
from .routing import (
    FactorRoute,
    FactorSpanDecision,
    FactorSpanRouteScores,
    SourceConditionedTriLoRALinear,
    factor_span_margins,
    four_state_from_logits,
)
from .training import (
    TrainingStage,
    configure_training_stage,
    formal_training_preflight_status,
)

__all__ = [
    "ARCHITECTURE_VERSION",
    "BackendStageConfiguration",
    "CANONICAL_ANSWERS",
    "CanonicalLanguagePlan",
    "DualSourceExplicitResidual",
    "ExactStageFTwoPassResult",
    "FactorRoute",
    "FactorSpanDecision",
    "FactorSpanRouteScores",
    "FactorTrainingContractError",
    "FourLineLanguageLoss",
    "HOLD_STATUS",
    "IMPLEMENTATION_EVIDENCE",
    "LANGUAGE_SPAN_ORDER",
    "LANGUAGE_SPAN_WEIGHT",
    "LanguagePlanContractError",
    "METHOD_SPEC_ID",
    "MOSDER_BACKEND_TYPES",
    "MolmoMoSDeRBackend",
    "MoSDeRBackendError",
    "MoSDeRFamilyBackendProtocol",
    "MoSDeRMotionSourceCore",
    "MoSDeRVisualBridge",
    "MotionSourceOutput",
    "NVILAMoSDeRBackend",
    "ObjectiveContractError",
    "OptimizerContractError",
    "ParsedMotionLanguage",
    "PUBLIC_METHOD_NAME",
    "QwenMoSDeRBackend",
    "StageFFactorLoss",
    "StageFCandidateTexts",
    "SUPPORTED_FAMILIES",
    "SourceConditionedTriLoRALinear",
    "TARGET_FAMILIES",
    "TrainingStage",
    "VisualBridgeOutput",
    "assemble_mosder_backend",
    "architecture_contract",
    "assert_mosder_frozen_base_unchanged",
    "audit_stage_adamw",
    "build_stage_adamw",
    "canonical_answer",
    "configure_training_stage",
    "factor_span_margins",
    "four_line_language_span_loss",
    "four_state_from_logits",
    "formal_training_preflight_status",
    "exact_two_pass_stage_f_backward",
    "load_local_mosder_backend",
    "method_parameter_ids",
    "parse_four_line_language",
    "plan_canonical_language",
    "snapshot_mosder_frozen_base",
    "stage_f_factor_loss",
    "stage_g_language_loss",
    "stage_r_language_loss",
    "validate_contract",
    "validate_language_plan",
    "validate_score_against_plan",
]
